export type PlayerProjection = {
  name: string;
  player_id: number;
  position: string;
  team: string;
  rushing_attempts: number;
  rushing_yards: number;
  rushing_touchdowns: number;
  first_downs: number;
  fumbles_lost: number;
  targets: number;
  catches: number;
  receiving_yards: number;
  receiving_touchdowns: number;
  passing_attempts: number;
  passing_completions: number;
  passing_interceptions: number;
  passing_yards: number;
  passing_touchdowns: number;
  passing_sacks: number;
  field_goals_attempted: number;
  field_goals_made: number;
  field_goals_missed: number;
  extra_point_kicking_attempts: number;
  extra_point_kicking_conversions: number;
  extra_point_kicking_misses: number;
  first_touchdown_scored: number;
  touchdowns_gte_1: number;
  touchdowns_gte_2: number;
  touchdowns_gte_3: number;
  rushing_receiving_touchdowns: number;
  rushing_receiving_yards: number;
  longest_catch: number;
  longest_rush: number;
  longest_pass: number;
  fantasy_points_half_ppr: number;
  fantasy_points_ppr: number;
  fantasy_points_non_ppr: number;
};

export type ScoringDetail = {
  GameKey: string;
  SeasonType: number;
  PlayerID: number;
  Team: string;
  Season: number;
  Week: number;
  ScoringType: string;
  Length: number;
  ScoringDetailID: number;
  PlayerGameID: number;
  ScoringPlayID: number;
};

type StadiumDetails = {
  StadiumID: number;
  Name: string;
  City: string;
  State: string;
  Country: string;
  Capacity: number;
  PlayingSurface: string;
  GeoLat: number;
  GeoLong: number;
  Type: string;
};

type Quarter = {
  QuarterID: number;
  ScoreID: number;
  Number: number;
  Name: string;
  Description: string;
  AwayTeamScore: number;
  HomeTeamScore: number;
  Updated: string;
  Created: string;
};

type Score = {
  GameKey: string;
  SeasonType: number;
  Season: number;
  Week: number;
  Date: string;
  AwayTeam: string;
  HomeTeam: string;
  AwayScore: number;
  HomeScore: number;
  Channel: string;
  PointSpread: number;
  OverUnder: number;
  Quarter: string;
  TimeRemaining: string | null;
  Possession: string | null;
  Down: number | null;
  Distance: number | null;
  YardLine: number | null;
  YardLineTerritory: string | null;
  RedZone: boolean | null;
  AwayScoreQuarter1: number;
  AwayScoreQuarter2: number;
  AwayScoreQuarter3: number;
  AwayScoreQuarter4: number;
  AwayScoreOvertime: number;
  HomeScoreQuarter1: number;
  HomeScoreQuarter2: number;
  HomeScoreQuarter3: number;
  HomeScoreQuarter4: number;
  HomeScoreOvertime: number;
  HasStarted: boolean;
  IsInProgress: boolean;
  IsOver: boolean;
  Has1stQuarterStarted: boolean;
  Has2ndQuarterStarted: boolean;
  Has3rdQuarterStarted: boolean;
  Has4thQuarterStarted: boolean;
  IsOvertime: boolean;
  DownAndDistance: string | null;
  QuarterDescription: string;
  StadiumID: number;
  LastUpdated: string;
  GeoLat: number | null;
  GeoLong: number | null;
  ForecastTempLow: number;
  ForecastTempHigh: number;
  ForecastDescription: string;
  ForecastWindChill: number;
  ForecastWindSpeed: number;
  AwayTeamMoneyLine: number;
  HomeTeamMoneyLine: number;
  Canceled: boolean;
  Closed: boolean;
  LastPlay: string | null;
  Day: string;
  DateTime: string;
  AwayTeamID: number;
  HomeTeamID: number;
  GlobalGameID: number;
  GlobalAwayTeamID: number;
  GlobalHomeTeamID: number;
  PointSpreadAwayTeamMoneyLine: number;
  PointSpreadHomeTeamMoneyLine: number;
  ScoreID: number;
  Status: string;
  GameEndDateTime: string;
  HomeRotationNumber: number;
  AwayRotationNumber: number;
  NeutralVenue: boolean;
  RefereeID: number;
  OverPayout: number;
  UnderPayout: number;
  HomeTimeouts: number | null;
  AwayTimeouts: number | null;
  DateTimeUTC: string;
  Attendance: number;
  IsClosed: boolean;
  StadiumDetails: StadiumDetails;
};

export type GameData = {
  Score: Score;
  Quarters: Quarter[];
};

export type PlayerGameStats = {
  GameKey: string;
  PlayerID: number;
  SeasonType: number;
  Season: number;
  GameDate: string;
  Week: number;
  Team: string;
  Opponent: string;
  HomeOrAway: "HOME" | "AWAY";
  Number: number;
  Name: string;
  Position: string;
  PositionCategory: string;
  Activated: number;
  Played: number;
  Started: number;
  PassingAttempts: number;
  PassingCompletions: number;
  PassingYards: number;
  PassingCompletionPercentage: number;
  PassingYardsPerAttempt: number;
  PassingYardsPerCompletion: number;
  PassingTouchdowns: number;
  PassingInterceptions: number;
  PassingRating: number;
  PassingLong: number;
  PassingSacks: number;
  PassingSackYards: number;
  RushingAttempts: number;
  RushingYards: number;
  RushingYardsPerAttempt: number;
  RushingTouchdowns: number;
  RushingLong: number;
  ReceivingTargets: number;
  Receptions: number;
  ReceivingYards: number;
  ReceivingYardsPerReception: number;
  ReceivingTouchdowns: number;
  ReceivingLong: number;
  Fumbles: number;
  FumblesLost: number;
  PuntReturns: number;
  PuntReturnYards: number;
  PuntReturnYardsPerAttempt: number;
  PuntReturnTouchdowns: number;
  PuntReturnLong: number;
  KickReturns: number;
  KickReturnYards: number;
  KickReturnYardsPerAttempt: number;
  KickReturnTouchdowns: number;
  KickReturnLong: number;
  SoloTackles: number;
  AssistedTackles: number;
  TacklesForLoss: number;
  Sacks: number;
  SackYards: number;
  QuarterbackHits: number;
  PassesDefended: number;
  FumblesForced: number;
  FumblesRecovered: number;
  FumbleReturnYards: number;
  FumbleReturnTouchdowns: number;
  Interceptions: number;
  InterceptionReturnYards: number;
  InterceptionReturnTouchdowns: number;
  BlockedKicks: number;
  SpecialTeamsSoloTackles: number;
  SpecialTeamsAssistedTackles: number;
  MiscSoloTackles: number;
  MiscAssistedTackles: number;
  Punts: number;
  PuntYards: number;
  PuntAverage: number;
  FieldGoalsAttempted: number;
  FieldGoalsMade: number;
  FieldGoalsLongestMade: number;
  ExtraPointsMade: number;
  TwoPointConversionPasses: number;
  TwoPointConversionRuns: number;
  TwoPointConversionReceptions: number;
  FantasyPoints: number;
  FantasyPointsPPR: number;
  ReceptionPercentage: number;
  ReceivingYardsPerTarget: number;
  Tackles: number;
  OffensiveTouchdowns: number;
  DefensiveTouchdowns: number;
  SpecialTeamsTouchdowns: number;
  Touchdowns: number;
  FantasyPosition: string;
  FieldGoalPercentage: number;
  PlayerGameID: number;
  FumblesOwnRecoveries: number;
  FumblesOutOfBounds: number;
  KickReturnFairCatches: number;
  PuntReturnFairCatches: number;
  PuntTouchbacks: number;
  PuntInside20: number;
  PuntNetAverage: number;
  ExtraPointsAttempted: number;
  BlockedKickReturnTouchdowns: number;
  FieldGoalReturnTouchdowns: number;
  Safeties: number;
  FieldGoalsHadBlocked: number;
  PuntsHadBlocked: number;
  ExtraPointsHadBlocked: number;
  PuntLong: number;
  BlockedKickReturnYards: number;
  FieldGoalReturnYards: number;
  PuntNetYards: number;
  SpecialTeamsFumblesForced: number;
  SpecialTeamsFumblesRecovered: number;
  MiscFumblesForced: number;
  MiscFumblesRecovered: number;
  ShortName: string;
  PlayingSurface: string;
  IsGameOver: boolean;
  SafetiesAllowed: number;
  Stadium: string;
  Temperature: number;
  Humidity: number;
  WindSpeed: number;
  FanDuelSalary: number;
  DraftKingsSalary: number;
  FantasyDataSalary: number;
  OffensiveSnapsPlayed: number;
  DefensiveSnapsPlayed: number;
  SpecialTeamsSnapsPlayed: number;
  OffensiveTeamSnaps: number;
  DefensiveTeamSnaps: number;
  SpecialTeamsTeamSnaps: number;
  VictivSalary: number | null;
  TwoPointConversionReturns: number;
  FantasyPointsFanDuel: number;
  FieldGoalsMade0to19: number;
  FieldGoalsMade20to29: number;
  FieldGoalsMade30to39: number;
  FieldGoalsMade40to49: number;
  FieldGoalsMade50Plus: number;
  FantasyPointsDraftKings: number;
  YahooSalary: number;
  FantasyPointsYahoo: number;
  InjuryStatus: string | null;
  InjuryBodyPart: string | null;
  InjuryStartDate: string | null;
  InjuryNotes: string | null;
  FanDuelPosition: string;
  DraftKingsPosition: string;
  YahooPosition: string;
  OpponentRank: number;
  OpponentPositionRank: number;
  InjuryPractice: string | null;
  InjuryPracticeDescription: string | null;
  DeclaredInactive: boolean;
  FantasyDraftSalary: number | null;
  FantasyDraftPosition: string | null;
  TeamID: number;
  OpponentID: number;
  Day: string;
  DateTime: string;
  GlobalGameID: number;
  GlobalTeamID: number;
  GlobalOpponentID: number;
  ScoreID: number;
  FantasyPointsFantasyDraft: number;
  OffensiveFumbleRecoveryTouchdowns: number | null;
  SnapCountsConfirmed: boolean;
  Updated: string;
  ScoringDetails: ScoringDetail[];
};
