import DashboardFeature from "@/components/dashboard/dashboard-feature";
export const metadata = {
  title: "web",
  description: "Generated by create-solana-dapp",
};
export default function Page() {
  return <DashboardFeature />;
}
