[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
tradetalk = "A13hqcQX4g2o57dW4vRQKem5G7YykugzPGyvda5YXijV"

[registry]
url = "https://quaint-hardworking-fire.solana-mainnet.quiknode.pro/5229b2c3c59e9aea2a1c583bafb9ad2d334d751a"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tradetalk.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://quaint-hardworking-fire.solana-mainnet.quiknode.pro/5229b2c3c59e9aea2a1c583bafb9ad2d334d751a"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms"

[[test.validator.clone]]
address = "wMNFSTkir3HgyZTsB7uqu3i7FA73grFCptPXgrZjksL"
